'use client'

import { useRouter } from 'next/navigation'
import { FormEvent, useEffect, useState } from 'react'
import { useNutrition, type UserGoals } from '@/app/components/NutritionContext'

export default function OnboardingPage() {
  const router = useRouter(); const { updateGoals, updateProfile } = useNutrition(); const [name, setName] = useState(''); const [weight, setWeight] = useState(65); const [height, setHeight] = useState(165); const [goal, setGoal] = useState<UserGoals['goalType']>('lose'); const [diet, setDiet] = useState('Vegetarian'); const [cuisine, setCuisine] = useState('Indian')
  useEffect(() => { const raw = localStorage.getItem('nourish-session'); if (!raw) { router.replace('/sign-in'); return }; setName(JSON.parse(raw).name) }, [router])
  function submit(event: FormEvent) { event.preventDefault(); const factor = goal === 'lose' ? -350 : goal === 'gain' ? 300 : 0; const calories = Math.max(1400, Math.round(10 * weight + 6.25 * height - 5 * 30 + 5 + factor)); const protein = Math.round(weight * (goal === 'gain' ? 1.8 : 1.5)); updateProfile({ name, initials: name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(), weightKg: weight, heightCm: height, allergies: [diet, cuisine] }); updateGoals({ goalType: goal, calories, proteinG: protein, carbsG: Math.round(calories * .48 / 4), fatG: Math.round(calories * .27 / 9) }); localStorage.setItem('nourish-onboarding-complete', 'true'); router.push('/dashboard') }
  return <main className="access-page"><form className="access-card onboarding" onSubmit={submit}><p className="landing-kicker">STEP 1 OF 1</p><h1>Let’s make this personal, {name || 'there'}.</h1><p>We’ll use these details to set a practical starting target. You can change everything later.</p><div className="form-row"><label>Weight (kg)<input min="35" max="250" type="number" value={weight} onChange={e => setWeight(+e.target.value)} /></label><label>Height (cm)<input min="120" max="230" type="number" value={height} onChange={e => setHeight(+e.target.value)} /></label></div><fieldset><legend>Your focus</legend><div className="choice-grid">{([['lose','Lose weight'],['maintain','Maintain'],['gain','Gain muscle']] as const).map(([value,label]) => <button type="button" onClick={() => setGoal(value)} className={goal === value ? 'selected' : ''} key={value}>{label}</button>)}</div></fieldset><div className="form-row"><label>Diet preference<select value={diet} onChange={e => setDiet(e.target.value)}><option>Vegetarian</option><option>Non-vegetarian</option><option>Vegan</option><option>Eggetarian</option></select></label><label>Favourite cuisine<select value={cuisine} onChange={e => setCuisine(e.target.value)}><option>Indian</option><option>South Indian</option><option>North Indian</option><option>Punjabi</option><option>Gujarati</option><option>Bengali</option></select></label></div><button className="landing-button" type="submit">Create my nutrition targets →</button></form></main>
}
